baseURL: https://blog.oscarizval.com/
languageCode: en-us
title: Digital Atlantis
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Archive
      url: archives
      weight: 5
    - name: Search
      url: search/
      weight: 10
    - name: Tags
      url: tags/
      weight: 10
    - name: WiKi
      url: https://github.com/adityatelange/hugo-PaperMod/wiki/
    - name: Discord
      url: https://discord.gg/ahpmTvhVmp

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  description: "My Blog params desc"
  author: Oscar Izquierdo Valentin

  defaultTheme: auto
  disableThemeToggle: false
  ShowShareButtons: false
  ShowReadingTime: true
  disableSpecial1stPost: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowToc: true
  comments: false

  cover:
    hidden: true # hide in home
    hiddenInList: true # hide on list pages 
    hiddenInSingle: false # hide on single page
    linkFullImages: false
    responsiveImages: false

  homeInfoParams:
    Title: "Hi there! \U0001F44B"
    Content: >
        Welcome to my personal blog! 
        This is where I share my thoughts, experiences, and insights on various topics that interest me. 
        Whether it's about technology, finances, or personal development, I aim to write pieces that are 
        informative, engaging, and thought-provoking.
  socialIcons:
    - name: github
      url: "https://github.com/oscar-izval"